[package]
name = "gpulda"
version = "0.0.1"
authors = [ "Alexander Terenin, Måns Magnusson and collaborators" ]

[dependencies]
libc = "0.2.0"
rand = "0.3"
lazy_static = "0.2"
structopt = "0.1.0"
structopt-derive = "0.1.6"
