[package]
name = "gpulda"
version = "0.0.1"
authors = [ "Alexander Terenin, Måns Magnusson, Willie Neiswanger and collaborators" ]

[dependencies]
byteorder = "1.2"
lazy_static = "0.2"
libc = "0.2.0"
memmap = "0.6.2"
rand = "0.3"
structopt = "0.1.0"
structopt-derive = "0.1.6"
